apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-svc
  labels:
    app: notify-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-svc
  template:
    metadata:
      name: notify-svc
      labels:
        app: notify-svc
    spec:
      containers:
        - name: notify-svc
          image: realshinchoku/carsties-notify-svc
          env:
            - name: RabbitMQ__Host
              value: rabbit-clusterip
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: rabbitUn
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: notify-secret
                  key: rabbitPw
---
apiVersion: v1
kind: Service
metadata:
  name: notify-clusterip
spec:
  type: ClusterIP
  selector:
    app: notify-svc
  ports:
    - port: 80
      targetPort: 80
