apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-svc
  labels:
    app: search-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-svc
  template:
    metadata:
      name: search-svc
      labels:
        app: search-svc
    spec:
      containers:
        - name: search-svc
          image: realshinchoku/carsties-search-svc
          env:
            - name: RabbitMQ__Host
              value: rabbit-clusterip
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: search-secret
                  key: rabbitUn
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: search-secret
                  key: rabbitPw
            - name: ConnectionStrings__MongoDbConnection
              valueFrom:
                secretKeyRef:
                  name: search-secret
                  key: connString
            - name: AuctionServiceUrl
              value: http://auction-clusterip
---
apiVersion: v1
kind: Service
metadata:
  name: search-clusterip
spec:
  type: ClusterIP
  selector:
    app: search-svc
  ports:
    - port: 80
      targetPort: 80
