name: deploy-notify

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - 'src/NotificationService/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v3
        with:
          context: "{{defaultContext}}"
          file: ./src/NotificationService/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/carsties-notify-svc:latest